console.log("Hello World!  ")
console.log("My name is Sumit Gohil \nThis is my 1st JavaScript Program using Node Environment")
console.log("Today we will do some basic experiment with js ")
console.log("5+5 = "+5+5)
console.log("(5+5) = "+(5+5))
console.log("(5+'5') = "+5+'5')
console.log("(5-'5') = "+(5-'5'))